config {
  type: "table",

  schema: "olist_gold",

  name: "dim_sellers",

  tags: ["phase_9", "gold", "dimension"],

  assertions: {
    nonNull: [
      "seller_id"
    ],

    uniqueKey: [
      "seller_id"
    ]
  },

  bigquery: {
    clusterBy: [
      "seller_state",
      "seller_city"
    ]
  }
}

SELECT

  s.seller_id,

  s.seller_zip_code_prefix,

  s.seller_city,

  s.seller_state,

  g.latitude AS seller_latitude,

  g.longitude AS seller_longitude,

  CASE
    WHEN g.zip_code_prefix IS NOT NULL THEN TRUE
    ELSE FALSE
  END AS has_geolocation

FROM ${ref("sellers")} AS s

LEFT JOIN ${ref("geolocation")} AS g
  ON s.seller_zip_code_prefix = g.zip_code_prefix