config {
  type: "assertion",
  schema: "olist_assertions",
  name: "customers_valid_values",
  tags: ["phase_10", "quality", "silver"]
}

SELECT
  customer_id,
  customer_unique_id,
  customer_zip_code_prefix,
  customer_city,
  customer_state

FROM ${ref("customers")}

WHERE

  customer_zip_code_prefix IS NULL

  OR customer_zip_code_prefix <= 0

  OR customer_city IS NULL

  OR customer_state IS NULL

  OR LENGTH(customer_state) != 2