config {
  type: "assertion",
  schema: "olist_assertions",
  name: "order_items_valid_values",
  tags: ["phase_10", "quality", "silver"]
}

SELECT

  order_id,
  order_item_id,
  product_id,
  seller_id,
  shipping_limit_ts,
  price,
  freight_value

FROM ${ref("order_items")}

WHERE

  order_id IS NULL

  OR order_item_id IS NULL

  OR order_item_id <= 0

  OR product_id IS NULL

  OR seller_id IS NULL

  OR price IS NULL

  OR price < 0

  OR freight_value IS NULL

  OR freight_value < 0