config {
  type: "table",

  schema: "olist_silver",

  name: "orders",
  
  tags: ["phase_8", "silver"],

  assertions: {
    nonNull: [
      "order_id",
      "customer_id",
      "order_status",
      "order_purchase_ts"
    ],

    uniqueKey: [
      "order_id"
    ],

    rowConditions: [
      "order_status IN ('delivered','shipped','canceled','unavailable','invoiced','processing','created','approved')",

      "order_purchase_ts IS NOT NULL"
    ]
  },

  bigquery: {
    partitionBy: "DATE(order_purchase_ts)",

    clusterBy: [
      "customer_id",
      "order_status"
    ]
  }
}


WITH source_data AS (

    SELECT

        order_id,

        customer_id,

        order_status,

        SAFE_CAST(
            order_purchase_timestamp
            AS TIMESTAMP
        ) AS order_purchase_ts,

        SAFE_CAST(
            order_approved_at
            AS TIMESTAMP
        ) AS order_approved_ts,

        SAFE_CAST(
            order_delivered_carrier_date
            AS TIMESTAMP
        ) AS order_delivered_carrier_ts,

        SAFE_CAST(
            order_delivered_customer_date
            AS TIMESTAMP
        ) AS order_delivered_customer_ts,

        SAFE_CAST(
            order_estimated_delivery_date
            AS TIMESTAMP
        ) AS order_estimated_delivery_ts

    FROM ${ref("orders_staging")}

),

deduplicated AS (

    SELECT *

    FROM source_data

    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY order_id
        ORDER BY order_purchase_ts DESC
    ) = 1

)


SELECT

    order_id,

    customer_id,

    order_status,

    order_purchase_ts,

    order_approved_ts,

    order_delivered_carrier_ts,

    order_delivered_customer_ts,

    order_estimated_delivery_ts

FROM deduplicated

WHERE order_id IS NOT NULL