config {
  type: "table",

  schema: "olist_silver",

  name: "order_items",

  tags: ["phase_8", "silver"],

  assertions: {
    nonNull: [
      "order_id",
      "order_item_id",
      "product_id",
      "seller_id",
      "price",
      "freight_value"
    ],

    uniqueKey: [
      "order_id",
      "order_item_id"
    ],

    rowConditions: [
      "order_item_id > 0",
      "price >= 0",
      "freight_value >= 0"
    ]
  },

  bigquery: {
    clusterBy: [
      "order_id",
      "product_id",
      "seller_id"
    ]
  }
}

WITH cleaned AS (

  SELECT

    TRIM(order_id) AS order_id,

    SAFE_CAST(order_item_id AS INT64) AS order_item_id,

    TRIM(product_id) AS product_id,

    TRIM(seller_id) AS seller_id,

    SAFE_CAST(
      shipping_limit_date AS TIMESTAMP
    ) AS shipping_limit_ts,

    SAFE_CAST(price AS NUMERIC) AS price,

    SAFE_CAST(freight_value AS NUMERIC) AS freight_value

  FROM ${ref("order_items_staging")}

),

deduplicated AS (

  SELECT *

  FROM cleaned

  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY order_id, order_item_id
    ORDER BY shipping_limit_ts DESC
  ) = 1

)

SELECT

  order_id,

  order_item_id,

  product_id,

  seller_id,

  shipping_limit_ts,

  price,

  freight_value,

  price + freight_value AS item_total_amount

FROM deduplicated

WHERE order_id IS NOT NULL
  AND order_item_id IS NOT NULL