config {
  type: "assertion",
  schema: "olist_assertions",
  name: "reviews_valid_values",
  tags: ["phase_10", "quality", "silver"]
}

SELECT
  review_id,
  order_id,
  review_score,
  review_creation_ts,
  review_answer_ts

FROM ${ref("reviews")}

WHERE
  review_id IS NULL

  OR order_id IS NULL

  OR review_score IS NULL

  OR review_score < 1
  OR review_score > 5

  OR review_creation_ts IS NULL