config {
  type: "table",

  schema: "olist_gold",

  name: "fact_payments",

  tags: ["phase_9", "gold", "fact"],

  assertions: {
    nonNull: [
      "order_id",
      "payment_sequential",
      "payment_type"
    ],

    uniqueKey: [
      "order_id",
      "payment_sequential"
    ]
  },

  bigquery: {
    partitionBy: "DATE(order_purchase_timestamp)",

    clusterBy: [
      "payment_type",
      "customer_unique_id"
    ]
  }
}

SELECT

  p.order_id,

  p.payment_sequential,

  p.payment_type,

  p.payment_installments,

  p.payment_value,

  fo.customer_id,

  fo.customer_unique_id,

  fo.order_status,

  fo.order_purchase_timestamp,

  CASE
    WHEN fo.order_id IS NOT NULL THEN TRUE
    ELSE FALSE
  END AS has_order_fact,

  CASE
    WHEN p.payment_installments > 1 THEN TRUE
    ELSE FALSE
  END AS is_installment_payment,

  CASE
    WHEN p.payment_type = 'credit_card' THEN TRUE
    ELSE FALSE
  END AS is_credit_card,

  CASE
    WHEN p.payment_type = 'voucher' THEN TRUE
    ELSE FALSE
  END AS is_voucher,

  CASE
    WHEN p.payment_type = 'boleto' THEN TRUE
    ELSE FALSE
  END AS is_boleto

FROM ${ref("payments")} AS p

LEFT JOIN ${ref("fact_orders")} AS fo
  ON p.order_id = fo.order_id